# Generated by Django 3.2.9 on 2023-02-04 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
